### ISSUE TITLE
Remove pyvenv.cfg

### ISSUE THREAD

**Issue by marjev** [dklarin/scrap-dev.to#1]
Ovo se dogodilo jer ste, pretpostavljam, commitali ovo prije nego ste dodali .gitignore ili zato što u .gitignore datoteci ovaj *.cfg file nije dodan na listu datoteka koje će se ignorirati.

Svakako bi trebao biti na listi.

Za početak:
- [ ] izbrisati *.cfg iz projektnog direktorija (jer sadrži podatke specifične za vaše okruženje)
- [ ] commitati promjene
- [ ] dodati iznimku u .gitignore ako ona već ne postoji
- [ ] testirati da vam buduće generiranje virtualnog okruženja tj. konfiguracijske datoteke git neće hvatati kao promjenu na aktivnom branchu

**Comment by dklarin** [comment]
Napravljeno
