### ISSUE TITLE
Improve / update README file

### ISSUE THREAD

**Issue by marjev** [dklarin/scrap-dev.to#2]
Možete unaprijediti popis paketa koje ste naveli u README datoteci tako što ćete iskoristiti bedževe poput ovih: https://shields.io/

Uz ime paketa bi bilo dobro istaknuti i verziju koja se koristila, tako da ljudi ne trebaju gledati direktno requirements.txt datoteku, već da im ta informacija bude odmah dostupna na površini.

**Comment by dklarin** [comment]
Napravljeno
