### ISSUE TITLE
Ime paketa na bedžu

### ISSUE THREAD

**Issue by marjev** [dklarin/scrap-dev.to#6]
Na bedžu za verziju stoji PyPi. Tu se inače stavlja ime paketa čija je verzija s desne strane bedža. U vašem slučaju, to bi trebao biti Scrapy.

Primjeri bedževa:
Na ovom repozitoriju https://github.com/vuejs/vue možete vidjeti kako je navedena verzija npm-a.

**Comment by dklarin** [comment]
Napravljeno
